<a href="https://colab.research.google.com/github/CBLBY/python-learning-/blob/master/Basic_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas learning

# 基础属性

In [0]:
import numpy as np
array = np.array([[1,2,3],[4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [0]:
#维度
ndim = array.ndim
print("ndim is" , ndim)

ndim is 2


In [0]:
#row and clums
shape = array.shape
print("行数与列数" , shape)

行数与列数 (2, 3)


In [0]:
#元素个数
size = array.size
print("个数是" , size)

个数是 6


数组创建

In [0]:
import numpy as np
x = np.array([[1,2,3],
             [4,5,6]])
print(x)


[[1 2 3]
 [4 5 6]]


In [0]:
#创建全零矩阵
x0 = np.zeros((3,2)) #输入全零数组格式
x00 = np.zeros_like(x, dtype = float)
print(x0)
print(x00)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
#创建全一矩阵
x1 = np.ones((2,2,4))
print(x1)
print(x1.shape)
x11 = np.ones_like(x, dtype = int)
print(x11)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
(2, 2, 4)
[[1 1 1]
 [1 1 1]]


In [0]:
#创建对角矩阵
xe = np.eye(3,3)
xd = np.diag([1,2,3,4])
print(xe)
print(xd)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [0]:
#创建全空数组
xblank = np.empty((2,3)) 
print(xblank)
if x0[0,0] == xblank[0,0] :
    print("Those all equal to zero")
else :
    print("The empty array is not equal to zero ")

[[0. 0. 0.]
 [0. 0. 0.]]
Those all equal to zero


In [0]:
#构造连续数组
xline = np.arange(0,11,2) #arange排列
print(xline)
xlinespace = np.linspace(0,11,2) #建立等差数列，告诉数组的数目
print(xlinespace)
xlog = np.logspace(2,3,4) #10^2如此类推
print(xlog)

[ 0  2  4  6  8 10]
[ 0. 11.]
[ 100.          215.443469    464.15888336 1000.        ]


In [0]:
changed_xline = xline.reshape(2,3) #形状要一致，不然会报错
print(changed_xline)
a = np.array([[1,2,3],
             [4,5,6]])
b = a.reshape(3,2) #一行一行数的顺序改变shape
print(b)

[[ 0  2  4]
 [ 6  8 10]]
[[1 2]
 [3 4]
 [5 6]]


In [0]:
#数组的轴
a = np.arange(24).reshape(2,3,4)
print(a)
print(np.ndim(a)) #三维数组
# 0轴为第一层，1轴为第二层，2轴为第三层
print(a[1])
print(a[1][0] [0]) #三个[]是三个轴，代表每个轴的第几个索引

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
12


#矩阵运算

In [0]:
#一维矩阵
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
plus = a + b #一维加法
print(plus)
sub = b - a #一维减法
print(sub)
mul = a*b #一维乘法
print(mul)
mul2 = a.dot(b) #点乘（内积） 1*5+2*6+3*7+4*8
print(mul2)

print(b > 6) #逻辑运算
d = np.arange(4) #直接生成范围内一位数组
print(d)

[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
70
[False False  True  True]
[0 1 2 3]


In [0]:
#多维运算
a = np.array([[1,2],
             [3,4]])
b = np.arange(5,9).reshape(2,2)
print(a,b)
c = a.dot(b) #第一种矩阵乘法
print(c)
c1 = np.dot(a,b) #第二种矩阵乘法
c2 = np.dot(b,a) #矩阵乘法没有交换律
print(c1)
print(c2)

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [0]:
#各种元素索引
a = np.arange(0,4).reshape(2,2)
print(a)
print("最小元素：", np.argmin(a))
print("最大元素：", np.argmax(a))
print("矩阵均值：", np.mean(a), np.average(a))
print("中位数：", np.median(a))

[[0 1]
 [2 3]]
最小元素： 0
最大元素： 3
矩阵均值： 1.5 1.5
中位数： 1.5


# 索引与切片


In [4]:
import numpy as np 
a = np.arange(0,9).reshape(3,3)
print(a)
print(a[:,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6]
